language: node_js
node_js:
  - "7"
cache:
  directories:
    - node_modules
install:
  - npm i markdown-spellcheck
script:
  - ./node_modules/markdown-spellcheck/bin/mdspell "**/*.md" "!node_modules/**" -nr --en-us
